# Generated by Django 6.0.7 on 2026-08-14 18:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('finance', '0001_initial'), ('finance', '0002_initial'), ('finance', '0003_clientcalculationresult_itemcalculationresult'), ('finance', '0004_rename_clients_price_cost_calculationresult_client_price_cost_and_more'), ('finance', '0005_rename_clients_price_cost_clientcalculationresult_client_price_cost'), ('finance', '0006_rename_clients_purchase_cost_itemcalculationresult_client_purchase_cost_and_more')]

    dependencies = [
        ('client', '0001_initial'),
        ('shipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cny_to_byn', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/BYN - себестоимость')),
                ('cny_to_byn_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/BYN - для клиента')),
                ('cny_to_rub', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/RUB - себестоимость')),
                ('cny_to_rub_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/RUB - для клиента')),
                ('usd_to_byn', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/BYN - себестоимость')),
                ('usd_to_byn_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/BYN - для клиента')),
                ('usd_to_rub', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/RUB - себестоимость')),
                ('usd_to_rub_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/RUB - для клиента')),
                ('rub_to_byn', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс RUB/BYN - себестоимость')),
                ('rub_to_byn_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс RUB/BYN - для клиента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обменный курс',
                'verbose_name_plural': 'Обменные курсы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('purchase_currency', models.CharField(choices=[('CNY', 'Китайский юань'), ('RUB', 'Российский Рубль'), ('USD', 'Американский доллар'), ('BYN', 'Белорусский рубль')], default='CNY', max_length=3, verbose_name='Основная валюта товаров')),
                ('final_currency', models.CharField(choices=[('CNY', 'Китайский юань'), ('RUB', 'Российский Рубль'), ('USD', 'Американский доллар'), ('BYN', 'Белорусский рубль')], default='BYN', max_length=3, verbose_name='Итоговая валюта')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Стоимость товара')),
                ('client_purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Стоимость товара для клиента')),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Логистические расходы')),
                ('buyer_commission_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Расчет комиссии байера, %')),
                ('price_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Общая себестоимость')),
                ('client_price_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Итого для клиентов')),
                ('profit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Прибыль')),
                ('expenses_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Расходы')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальный расчет')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_results', to='shipment.shipment', verbose_name='Поставка')),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_results', to='finance.exchangerate', verbose_name='Обменный курс')),
            ],
            options={
                'verbose_name': 'Результат расчета',
                'verbose_name_plural': 'Результаты расчетов',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_actual', True)), fields=('shipment',), name='unique_actual_calculation_per_shipment')],
            },
        ),
        migrations.CreateModel(
            name='ClientCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Комиссия байера, %')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость товаров')),
                ('client_purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость товаров для клиента')),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Доля логистики')),
                ('expenses_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Расходы клиента')),
                ('buyer_commission_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Комиссия байера')),
                ('price_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость по клиенту')),
                ('calculation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_results', to='finance.calculationresult', verbose_name='Общий результат расчета')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_calculation_results', to='client.client', verbose_name='Клиент')),
                ('client_price_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого клиенту')),
                ('profit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Результат расчета клиента',
                'verbose_name_plural': 'Результаты расчетов клиентов',
                'ordering': ['client__full_name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость товара')),
                ('client_purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость товара для клиентов')),
                ('allocation_basis', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Вес или объем для распределения')),
                ('allocation_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Доля товара в поставке')),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Доля логистики товара')),
                ('direct_expenses_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Прямые расходы товара')),
                ('distributed_expenses_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Распределенные общие расходы')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого по товару')),
                ('client_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='finance.clientcalculationresult', verbose_name='Расчет клиентов')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_calculation_results', to='shipment.shipmentitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Результат расчета товара',
                'verbose_name_plural': 'Результаты расчетов по товарам',
                'ordering': ['item__name'],
            },
        ),
    ]
