# Generated by Django 6.0.7 on 2026-07-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('base_currency', models.CharField(default='CNY', max_length=3, verbose_name='Валюта базовая')),
                ('counter_currency', models.CharField(max_length=3, verbose_name='Валюта котировки')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Стоимость товара, ¥')),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Логистические расходы')),
                ('buyer_commission_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Расчет комиссии байера, %')),
                ('price_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Расчет себестоимости')),
                ('client_price_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Итого для клиента')),
                ('profit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Прибыль')),
                ('add_services', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Дополнительные услуги')),
            ],
            options={
                'verbose_name_plural': 'Результаты расчетов',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date', models.DateField(verbose_name='Дата')),
                ('cny_to_byn', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/BYN - себестоимость')),
                ('cny_to_byn_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/BYN - для клиента')),
                ('cny_to_rub', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/RUB - себестоимость')),
                ('cny_to_rub_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс СNY/RUB - для клиента')),
                ('usd_to_byn', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/BYN - себестоимость')),
                ('usd_to_byn_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/BYN - для клиента')),
                ('usd_to_rub', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/RUB - себестоимость')),
                ('usd_to_rub_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/RUB - для клиента')),
                ('rub_to_byn', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс RUB/BYN - себестоимость')),
                ('rub_to_byn_client', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс RUB/BYN - для клиента')),
            ],
            options={
                'verbose_name_plural': 'Обменные курсы',
            },
        ),
    ]
