# Generated by Django 6.0.7 on 2026-08-17 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("finance", "0001_initial"),
        ("shipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationresult",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculation_results",
                to="shipment.shipment",
                verbose_name="Поставка",
            ),
        ),
        migrations.AddField(
            model_name="clientcalculationresult",
            name="calculation_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_results",
                to="finance.calculationresult",
                verbose_name="Общий результат расчета",
            ),
        ),
        migrations.AddField(
            model_name="clientcalculationresult",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_calculation_results",
                to="client.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange_rates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="calculationresult",
            name="exchange_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calculation_results",
                to="finance.exchangerate",
                verbose_name="Обменный курс",
            ),
        ),
        migrations.AddField(
            model_name="itemcalculationresult",
            name="client_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_results",
                to="finance.clientcalculationresult",
                verbose_name="Расчет клиентов",
            ),
        ),
        migrations.AddField(
            model_name="itemcalculationresult",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_calculation_results",
                to="shipment.shipmentitem",
                verbose_name="Товар",
            ),
        ),
        migrations.AddConstraint(
            model_name="calculationresult",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_actual", True)),
                fields=("shipment",),
                name="unique_actual_calculation_per_shipment",
            ),
        ),
    ]
