# Generated by Django 6.0.7 on 2026-07-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationresult",
            name="shipment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculation_result",
                to="shipment.shipment",
                verbose_name="Поставка",
            ),
        ),
        migrations.AddField(
            model_name="calculationresult",
            name="exchange_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculation_result",
                to="finance.exchangerate",
                verbose_name="Обменный курс",
            ),
        ),
    ]
