# Generated by Django 6.0.7 on 2026-07-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationresult',
            old_name='add_services',
            new_name='additional_services',
        ),
    ]
