# Generated by Django 6.0.7 on 2026-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationresult",
            name="logistics_cost_rub",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=16,
                verbose_name="Общая стоимость доставки в RUB",
            ),
        ),
    ]
