# Generated by Django 6.0.7 on 2026-07-31 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationresult',
            name='exchange_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_result', to='finance.exchangerate', verbose_name='Обменный курс'),
            preserve_default=False,
        ),
    ]
