# Generated by Django 6.0.7 on 2026-08-17 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import config.model_choices


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
        ("finance", "0003_calculationresult_logistics_cost_rub"),
        ("shipment", "0004_alter_shipment_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Сумма оплаты",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "Китайский юань"),
                            ("RUB", "Российский Рубль"),
                            ("USD", "Американский доллар"),
                            ("BYN", "Белорусский рубль"),
                        ],
                        default=config.model_choices.SettlementFinalCurrency,
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата оплаты"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Примечание"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="client.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_payments",
                        to="shipment.shipment",
                        verbose_name="Поставка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата клиента",
                "verbose_name_plural": "Оплаты клиентов",
                "ordering": ["-paid_at"],
            },
        ),
    ]
