# Generated by Django 6.0.7 on 2026-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_add_services_calculationresult_additional_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationresult',
            name='client_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Стоимость товара для клиента, ¥'),
        ),
    ]
