# Generated by Django 6.0.7 on 2026-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_clientpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpayment",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CNY", "Китайский юань"),
                    ("RUB", "Российский Рубль"),
                    ("USD", "Американский доллар"),
                    ("BYN", "Белорусский рубль"),
                ],
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
