# Generated by Django 6.0.7 on 2026-08-19 05:43

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_alter_clientpayment_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Сумма оплаты",
            ),
        ),
    ]
