# Generated by Django 6.0.7 on 2026-08-17 07:11

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=128, verbose_name="Полное имя"),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "buyer_commission_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal(0)),
                            django.core.validators.MaxValueValidator(Decimal(100)),
                        ],
                        verbose_name="Комиссия байера, %",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": "clients",
                "ordering": ["full_name"],
            },
        ),
    ]
