# Generated by Django 6.0.7 on 2026-07-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='buyer_commission_precent',
            new_name='buyer_commission_percent',
        ),
    ]
