# Generated by Django 6.0.7 on 2026-07-29 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('finance', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('article', models.CharField(blank=True, max_length=60, verbose_name='Артикул')),
                ('link', models.URLField(blank=True, max_length=100, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tariff_one_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Тариф за 1 кг')),
                ('tariff_currency', models.CharField(choices=[('CNY', 'Китайский юань'), ('RUB', 'Российский Рубль'), ('USD', 'Американский доллар'), ('BYN', 'Белорусский рубль')], default='USD', max_length=10, verbose_name='Валюта тарифа')),
                ('settlement_final_currency', models.CharField(choices=[('RUB', 'Российский Рубль'), ('BYN', 'Белорусский рубль')], default='BYN', max_length=10, verbose_name='Валюта итогового расчета')),
                ('number', models.CharField(max_length=30, verbose_name='Номер поставки')),
                ('status', models.CharField(default='Создана', max_length=30, verbose_name='Статус поставки')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вес, кг')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Объем, м3')),
                ('logistic_calculation_type', models.CharField(choices=[('weight', 'По весу'), ('volume', 'По объему')], default='weight', max_length=30, verbose_name='Способ расчета логистики')),
                ('tariff_one_m3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Тариф за 1 м3')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='finance.exchangerate', verbose_name='Обменные курсы валют')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='logistics.route', verbose_name='Маршрут поставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'db_table': 'shipment',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tracking_number', models.CharField(blank=True, max_length=130, null=True, verbose_name='Трек-номер')),
                ('product_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на товар')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество, шт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('price_currency', models.CharField(choices=[('CNY', 'Китайский юань'), ('RUB', 'Российский Рубль'), ('USD', 'Американский доллар'), ('BYN', 'Белорусский рубль')], default='CNY', max_length=10, verbose_name='Валюта цены')),
                ('inspection_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Проверка товара')),
                ('photo_report_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фотоотчет')),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Упаковка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='client.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shipment.product', verbose_name='Товар')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shipment.shipment', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Товар для отправки',
                'verbose_name_plural': 'Товары для отправки',
                'ordering': ['-quantity', '-price'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expense_type', models.CharField(choices=[('transport', 'Международная доставка'), ('transport_company', 'Доставка транспортной компанией'), ('insurance', 'Страхование'), ('loading', 'Загрузка'), ('unloading', 'Отгрузка'), ('other', 'Прочее')], max_length=40, verbose_name='Тип расходов')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('CNY', 'Китайский юань'), ('RUB', 'Российский Рубль'), ('USD', 'Американский доллар'), ('BYN', 'Белорусский рубль')], max_length=10, verbose_name='Валюта')),
                ('note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='shipment.shipment')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='shipment.shipmentitem', verbose_name='Конкретный товар')),
            ],
            options={
                'verbose_name_plural': 'Расходы',
                'ordering': ['-amount'],
            },
        ),
    ]
