# Generated by Django 6.0.7 on 2026-07-12 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('number', models.CharField(max_length=30, verbose_name='Номер поставки')),
                ('route', models.CharField(choices=[('CHINA-RUSSIA', 'Ch Ru'), ('CHINA-BELARUS', 'Ch By')], verbose_name='Маршрут поставки')),
                ('status', models.CharField(max_length=30, verbose_name='Статус поставки')),
                ('note', models.CharField(max_length=255, verbose_name='Примечание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'db_table': 'shipment',
                'ordering': ['number'],
            },
        ),
    ]
