# Generated by Django 6.0.7 on 2026-08-17 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("china_russia", "Китай-Россия"),
                            ("china_belarus", "Китай-Беларусь"),
                            ("china_russia_belarus", "Китай-Россия-Беларусь"),
                        ],
                        default="china_belarus",
                        max_length=40,
                        verbose_name="Маршрут поставки",
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("air", "Авиационный"),
                            ("auto", "Автомобильный"),
                            ("sea", "Морской"),
                            ("rail", "Железнодорожный"),
                        ],
                        default="auto",
                        max_length=30,
                        verbose_name="Тип транспорта",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=30, verbose_name="Номер поставки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("edite", "Редактируется"),
                            ("calculated", "Рассчитана"),
                            ("closed", "Закрыта"),
                        ],
                        default="edite",
                        max_length=20,
                        verbose_name="Статус поставки",
                    ),
                ),
                (
                    "logistic_calculation_type",
                    models.CharField(
                        choices=[("weight", "По весу"), ("volume", "По объему")],
                        default="weight",
                        max_length=30,
                        verbose_name="Способ расчета логистики",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Фактический вес поставки, кг",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Фактический объем поставки, м3",
                    ),
                ),
                (
                    "tariff_one_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Тариф за 1 кг",
                    ),
                ),
                (
                    "tariff_one_m3",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Тариф за 1 м3",
                    ),
                ),
                (
                    "tariff_currency",
                    models.CharField(
                        choices=[
                            ("CNY", "Китайский юань"),
                            ("RUB", "Российский Рубль"),
                            ("USD", "Американский доллар"),
                            ("BYN", "Белорусский рубль"),
                        ],
                        default="USD",
                        max_length=10,
                        verbose_name="Валюта тарифа",
                    ),
                ),
                (
                    "settlement_final_currency",
                    models.CharField(
                        choices=[
                            ("RUB", "Российский Рубль"),
                            ("BYN", "Белорусский рубль"),
                        ],
                        default="BYN",
                        editable=False,
                        max_length=10,
                        verbose_name="Валюта итогового расчета",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Примечание"
                    ),
                ),
                (
                    "exchange_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="finance.exchangerate",
                        verbose_name="Обменные курсы валют",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка",
                "verbose_name_plural": "Поставки",
                "db_table": "shipment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Наименование товара"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=130, null=True, verbose_name="Трек-номер"
                    ),
                ),
                (
                    "product_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на товар"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество, шт"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за единицу"
                    ),
                ),
                (
                    "price_currency",
                    models.CharField(
                        choices=[
                            ("CNY", "Китайский юань"),
                            ("RUB", "Российский Рубль"),
                            ("USD", "Американский доллар"),
                            ("BYN", "Белорусский рубль"),
                        ],
                        default="CNY",
                        max_length=3,
                        verbose_name="Валюта цены",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Общий вес позиции, кг",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=10,
                        verbose_name="Общий объем позиции, м3",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_items",
                        to="client.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipment.shipment",
                        verbose_name="Поставка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар для отправки",
                "verbose_name_plural": "Товары для отправки",
                "ordering": ["-client_id", "-name"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("transport_company", "Доставка транспортной компанией"),
                            ("insurance", "Страхование"),
                            ("loading", "Погрузка"),
                            ("unloading", "Разгрузка"),
                            ("inspection", "Проверка товара"),
                            ("photo_report", "Фотоотчет"),
                            ("item_packaging", "Упаковка товара"),
                            ("shipments_packaging", "Упаковка посылки"),
                            ("customs", "Таможенные расходы"),
                            ("storage", "Хранение"),
                            ("other", "Прочее"),
                        ],
                        max_length=40,
                        verbose_name="Тип расходов",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CNY", "Китайский юань"),
                            ("RUB", "Российский Рубль"),
                            ("USD", "Американский доллар"),
                            ("BYN", "Белорусский рубль"),
                        ],
                        default="USD",
                        max_length=10,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Примечание"
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="shipment.shipment",
                        verbose_name="Поставка",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="shipment.shipmentitem",
                        verbose_name="Конкретный товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расход поставки",
                "verbose_name_plural": "Расходы поставки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                fields=("user", "number"), name="unique_shipment_number_per_user"
            ),
        ),
    ]
