# Generated by Django 6.0.7 on 2026-07-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='note',
            field=models.CharField(max_length=255, null=True, verbose_name='Примечание'),
        ),
    ]
