# Generated by Django 6.0.7 on 2026-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentitem",
            name="volume",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Общий объем позиции, м3",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                verbose_name="Общий вес позиции, кг",
            ),
        ),
    ]
