# Generated by Django 6.0.7 on 2026-08-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentexpense',
            name='currency',
            field=models.CharField(choices=[('CNY', 'Китайский юань'), ('RUB', 'Российский Рубль'), ('USD', 'Американский доллар'), ('BYN', 'Белорусский рубль')], default='USD', max_length=10, verbose_name='Валюта'),
        ),
    ]
