# Generated by Django 6.0.7 on 2026-08-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_shipmentitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='volume',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Общий объем позиции, м3'),
        ),
    ]
