# Generated by Django 6.0.7 on 2026-08-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipment", "0003_alter_shipmentitem_volume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                verbose_name="Фактический вес поставки, кг",
            ),
        ),
    ]
