# Generated by Django 6.0.7 on 2026-08-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_alter_clientpayment_amount"),
        ("shipment", "0004_alter_shipment_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="exchange_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="finance.exchangerate",
                verbose_name="Обменный курс валют",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="tariff_currency",
            field=models.CharField(
                choices=[
                    ("CNY", "Китайский юань"),
                    ("RUB", "Российский Рубль"),
                    ("USD", "Американский доллар"),
                    ("BYN", "Белорусский рубль"),
                ],
                default="USD",
                max_length=3,
                verbose_name="Валюта тарифа",
            ),
        ),
    ]
