# Generated by Django 6.0.7 on 2026-07-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_shipmentitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentitem',
            options={'ordering': ['-quantity', '-price'], 'verbose_name': 'Товар для отправки', 'verbose_name_plural': 'Товары для отправки'},
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=60, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='inspection_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='packaging_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='photo_report_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ShipmentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('transport', 'Transport'), ('transport_company', 'Tc'), ('insurance', 'Insurance'), ('loading', 'Loading'), ('unloading', 'Unloading'), ('packaging', 'Packaging'), ('photo_report', 'Photo'), ('inspection', 'Inspection'), ('customs', 'Customs'), ('other', 'Other')], max_length=40, verbose_name='Тип расходов')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('CNY', 'Cny'), ('RUB', 'Rub'), ('BYN', 'Byn')], max_length=10, verbose_name='Валюта')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='shipment.shipment')),
            ],
            options={
                'verbose_name_plural': 'Расходы',
                'ordering': ['-amount'],
            },
        ),
    ]
