# Generated by Django 6.0.7 on 2026-09-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_alter_shipment_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='На складе'),
        ),
    ]
