# Generated by Django 6.0.7 on 2026-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "dispatch_country",
                    models.CharField(max_length=100, verbose_name="Страна отправления"),
                ),
                (
                    "destination_country",
                    models.CharField(max_length=100, verbose_name="Страна назначения"),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("air", "Авиационный"),
                            ("auto", "Автомобильный"),
                            ("sea", "Морской"),
                            ("rail", "Железнодорожный"),
                        ],
                        max_length=100,
                        verbose_name="Тип транспорта",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный маршрут"),
                ),
            ],
            options={
                "verbose_name": "Маршрут доставки",
                "verbose_name_plural": "Маршруты доставки",
                "ordering": [
                    "dispatch_country",
                    "destination_country",
                    "transport_type",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "dispatch_country",
                            "destination_country",
                            "transport_type",
                        ),
                        name="unique_country_and_transport_type",
                    )
                ],
            },
        ),
    ]
